// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK4lFQmZqsvPJDmWy0RY1RGMuKlmEfT7w',
    appId: '1:316360509652:web:81359aa2b9e55c6ad75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    authDomain: 'quicklick-9fbbb.firebaseapp.com',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzOjZEtTecyi4m99Xodxcax6cx2k864bo',
    appId: '1:316360509652:android:bf62bfc91c600db9d75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmSP4F_kMUuqmTc0you3AQVsglT6r9vz8',
    appId: '1:316360509652:ios:f897aba8a948311bd75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
    iosBundleId: 'com.quicklick.quicklick',
  );
}
