// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzOjZEtTecyi4m99Xodxcax6cx2k864bo',
    appId: '1:316360509652:android:fd69cc46657ca88fd75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK4lFQmZqsvPJDmWy0RY1RGMuKlmEfT7w',
    appId: '1:316360509652:web:9f74bb81e377f244d75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    authDomain: 'quicklick-9fbbb.firebaseapp.com',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
    measurementId: 'G-2C5NKECC56',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmSP4F_kMUuqmTc0you3AQVsglT6r9vz8',
    appId: '1:316360509652:ios:de42205e35192affd75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
    androidClientId: '316360509652-9an83rdsb8p45t1kn8qkklvopqigqr0q.apps.googleusercontent.com',
    iosClientId: '316360509652-40r0s8b42326i0bgpmlmovr0p7kuc3nu.apps.googleusercontent.com',
    iosBundleId: 'com.quiqliq.quiqliq',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmSP4F_kMUuqmTc0you3AQVsglT6r9vz8',
    appId: '1:316360509652:ios:de42205e35192affd75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
    androidClientId: '316360509652-9an83rdsb8p45t1kn8qkklvopqigqr0q.apps.googleusercontent.com',
    iosClientId: '316360509652-40r0s8b42326i0bgpmlmovr0p7kuc3nu.apps.googleusercontent.com',
    iosBundleId: 'com.quiqliq.quiqliq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK4lFQmZqsvPJDmWy0RY1RGMuKlmEfT7w',
    appId: '1:316360509652:web:f2c81a9086ef2d96d75341',
    messagingSenderId: '316360509652',
    projectId: 'quicklick-9fbbb',
    authDomain: 'quicklick-9fbbb.firebaseapp.com',
    storageBucket: 'quicklick-9fbbb.firebasestorage.app',
    measurementId: 'G-H3RVM5QYL0',
  );

}